server:
  port: 8080

spring:
  datasource:
    url: "jdbc:h2:file:./budget-assistant"
    username: "test"
    initialization-mode: always
    continue-on-error: true
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: "update"
    show-sql: true
  h2:
    console:
      enabled: true
      path: "/console"
