server:
  port: 8080

spring:
  datasource:
    url: "jdbc:h2:file:./budget-assistant"
    username: "test"
    initialization-mode: always
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: "create"
  h2:
    console:
      enabled: true
      path: "/console"
